name: CI/CD Pipeline
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    branches:
      - main
jobs:
  #Test's job
  tests:
    name: Unit tests
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    #Job's steps
    steps:
      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - uses: actions/checkout@v1
      #Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      #Run Tests
      - name: Run Tests
        run: mvn -B test
  #build Stage
  build:
    name: Build Artifact
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
    #Build Application Using Maven
      - name: Build with maven
        run: mvn - B package -DskipTests --file pom.xml
      #BUILD THE ARTIFACT
      - name: Upload War Artifact
        #This upload our artifacts from workflow allowing to share data between jobs and store data once a workflow is complete.
        uses: actions/upload-artifact@v2
        with:
          #set artifact name
          name: artifact
          #From:
          path: target/data-0.0.1-SNAPSHOT.war